Add sidekiq/redis
davidBentoPereira/spotify-library pull request #1
Opened 2024-03-24 21:15 UTC by Crysicia

Basic sidekiq config

2024-03-25 13:48 UTC, davidBentoPereira requested changes

2024-03-25 13:48 UTC, davidBentoPereira commented on .env.development
> +REDIS_URL=
On a vraiment besoin de cette REDIS_URL en environnement de développement ?
Je pense qu'on en a surtout besoin pour la Prod, mais en local j'arrive à faire tourner Sidekiq & Redis juste en lançant mes commandes `redis-server` et `bundle exec sidekiq`.

2024-03-25 13:50 UTC, davidBentoPereira commented on .env.development
> +REDIS_URL=
D'ailleurs, il manque ces 2 lignes là dans le fichier `Procfile.dev` :

```
web: bin/rails server -p 3000
css: bin/rails tailwindcss:watch
+ redis: redis-server
+ sidekiq: bundle exec sidekiq
```

2024-03-25 13:52 UTC, davidBentoPereira commented on .env.development
> +REDIS_URL=
(J'ai commit cet ajout, tu me dis si t'es pas d'accord)

2024-03-25 14:17 UTC, davidBentoPereira commented on .env.development
> +REDIS_URL=
J'ai aussi rajouté un job et un test basic pour montrer que Sidekiq fonctionne correctement.

2024-03-25 14:18 UTC, davidBentoPereira commented
@Crysicia je te laisse review mes modifs por favor 🙏

2024-03-25 14:20 UTC, Crysicia commented
> @Crysicia je te laisse review mes modifs por favor 🙏

Je fais ça dès que j'ai un peu de time 😅

2024-03-25 14:25 UTC, davidBentoPereira commented
> > @Crysicia je te laisse review mes modifs por favor 🙏
> 
> Je fais ça dès que j'ai un peu de time 😅

Pas de soucis mec, y'a le time 😉

2024-03-26 08:18 UTC, Crysicia commented on .env.development
> +REDIS_URL=
Bien ouej'
Effectivement c'est plus clair!

2024-03-26 08:18 UTC, Crysicia commented on .env.development
> +REDIS_URL="redis://localhost:6379" # default connection for localhost
Il manque l'id de la db

```suggestion
REDIS_URL="redis://localhost:6379/0" # default connection for localhost
```

2024-03-26 08:25 UTC, Crysicia commented
Mec t'es trop vif, jétais en train de rajouter l'id de la db aussi xD

2024-03-26 08:36 UTC, davidBentoPereira commented
> Mec t'es trop vif, jétais en train de rajouter l'id de la db aussi xD

Ah ah, désolé, j'étais en train de taffer sur l'ajout du job SyncFollowedArtists basé sur cette PR donc je l'ai fait direct 😛

2024-03-26 08:36 UTC, davidBentoPereira commented
@Crysicia si c'est OK pour toi je peux merge ?

2024-03-26 08:53 UTC, Crysicia commented
Yes all good 👍

2024-03-26 08:54 UTC, merged